#ifndef MY_MODEL_H
#define MY_MODEL_H
#include "iec61850_server.h"
#include "hal_thread.h"
#include <signal.h>
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include <string.h>
#include <unistd.h>
#include "static_model.h"

enum type1
{
	boolen_value, timestamp_value, int_value, float_value, Dbpos_type_value
};
//read
struct get_api
{

    char* str;
    const DataAttribute* var;
    enum type1 type;
};
//write
struct controlbyUDP{
    char* str;     
    DataAttribute* var;  
    const DataAttribute* var1;
    DataAttribute* time;
    int timeupload;
};
struct controlbyUDP EFG[500] = {	
	
	{"IEDMODEL_DER3_GGIO1_SPCSO1_stVal", IEDMODEL_DER3_GGIO1_SPCSO1_stVal, IEDMODEL_DER3_GGIO1_SPCSO1_stVal, IEDMODEL_DER3_GGIO1_SPCSO1_t, 1},

	{"IEDMODEL_DER3_GGIO1_OpCntRs_stVal", IEDMODEL_DER3_GGIO1_OpCntRs_stVal, IEDMODEL_DER3_GGIO1_OpCntRs_stVal, IEDMODEL_DER3_GGIO1_OpCntRs_t, 1},
	{"IEDMODEL_DER3_GGIO1_DPCSO1_stVal", IEDMODEL_DER3_GGIO1_DPCSO1_stVal, IEDMODEL_DER3_GGIO1_DPCSO1_stVal, IEDMODEL_DER3_GGIO1_DPCSO1_t, 1},
	{"IEDMODEL_DER3_GGIO1_ISCSO1_stVal", IEDMODEL_DER3_GGIO1_ISCSO1_stVal, IEDMODEL_DER3_GGIO1_ISCSO1_stVal, IEDMODEL_DER3_GGIO1_ISCSO1_t, 1},

	{"IEDMODEL_DER3_MMXU1_TotW_mag", IEDMODEL_DER3_MMXU1_TotW_mag_i, IEDMODEL_DER3_MMXU1_TotW_mag_i, IEDMODEL_DER3_MMXU1_TotW_t, 1},
	{"IEDMODEL_DER3_MMXU1_TotVAr_mag", IEDMODEL_DER3_MMXU1_TotVAr_mag_i, IEDMODEL_DER3_MMXU1_TotVAr_mag_i, IEDMODEL_DER3_MMXU1_TotVAr_t, 1},
	{"IEDMODEL_DER3_MMXU1_TotVA_mag", IEDMODEL_DER3_MMXU1_TotVA_mag_i, IEDMODEL_DER3_MMXU1_TotVA_mag_i, IEDMODEL_DER3_MMXU1_TotVA_t, 1},
	{"IEDMODEL_DER3_MMXU1_TotPF_mag", IEDMODEL_DER3_MMXU1_TotPF_mag_i, IEDMODEL_DER3_MMXU1_TotPF_mag_i, IEDMODEL_DER3_MMXU1_TotPF_t, 1},
	{"IEDMODEL_DER3_MMXU1_Hz_mag", IEDMODEL_DER3_MMXU1_Hz_mag_i, IEDMODEL_DER3_MMXU1_Hz_mag_i, IEDMODEL_DER3_MMXU1_Hz_t, 1},
	{"IEDMODEL_DER3_MMXU1_PPV_phsAB", IEDMODEL_DER3_MMXU1_PPV_phsAB_cVal_mag_i, IEDMODEL_DER3_MMXU1_PPV_phsAB_cVal_mag_i, IEDMODEL_DER3_MMXU1_PPV_phsAB_t, 1},
	{"IEDMODEL_DER3_MMXU1_PPV_phsBC", IEDMODEL_DER3_MMXU1_PPV_phsBC_cVal_mag_i, IEDMODEL_DER3_MMXU1_PPV_phsBC_cVal_mag_i, IEDMODEL_DER3_MMXU1_PPV_phsBC_t, 1},
	{"IEDMODEL_DER3_MMXU1_PPV_phsCA", IEDMODEL_DER3_MMXU1_PPV_phsCA_cVal_mag_i, IEDMODEL_DER3_MMXU1_PPV_phsCA_cVal_mag_i, IEDMODEL_DER3_MMXU1_PPV_phsCA_t, 1},
	{"IEDMODEL_DER3_MMXU1_PNV_phsA", IEDMODEL_DER3_MMXU1_PNV_phsA_cVal_mag_i, IEDMODEL_DER3_MMXU1_PNV_phsA_cVal_mag_i, IEDMODEL_DER3_MMXU1_PNV_phsA_t, 1},
	{"IEDMODEL_DER3_MMXU1_PNV_phsA", IEDMODEL_DER3_MMXU1_PNV_phsA_cVal_mag_f, IEDMODEL_DER3_MMXU1_PNV_phsA_cVal_mag_f, IEDMODEL_DER3_MMXU1_PNV_phsA_t, 1},

	{"IEDMODEL_DER3_MMXU1_PNV_phsB", IEDMODEL_DER3_MMXU1_PNV_phsB_cVal_mag_i, IEDMODEL_DER3_MMXU1_PNV_phsB_cVal_mag_i, IEDMODEL_DER3_MMXU1_PNV_phsB_t, 1},
	{"IEDMODEL_DER3_MMXU1_PNV_phsC", IEDMODEL_DER3_MMXU1_PNV_phsC_cVal_mag_i, IEDMODEL_DER3_MMXU1_PNV_phsC_cVal_mag_i, IEDMODEL_DER3_MMXU1_PNV_phsC_t, 1},
	{"IEDMODEL_DER3_MMXU1_A_phsA", IEDMODEL_DER3_MMXU1_A_phsA_cVal_mag_i, IEDMODEL_DER3_MMXU1_A_phsA_cVal_mag_i, IEDMODEL_DER3_MMXU1_A_phsA_t, 1},
	{"IEDMODEL_DER3_MMXU1_A_phsB", IEDMODEL_DER3_MMXU1_A_phsB_cVal_mag_i, IEDMODEL_DER3_MMXU1_A_phsB_cVal_mag_i, IEDMODEL_DER3_MMXU1_A_phsB_t, 1},
	{"IEDMODEL_DER3_MMXU1_A_phsC", IEDMODEL_DER3_MMXU1_A_phsC_cVal_mag_i, IEDMODEL_DER3_MMXU1_A_phsC_cVal_mag_i, IEDMODEL_DER3_MMXU1_A_phsC_t, 1},
	{"IEDMODEL_DER3_MMDC1_Watt_mag", IEDMODEL_DER3_MMDC1_Watt_mag_i, IEDMODEL_DER3_MMDC1_Watt_mag_i, IEDMODEL_DER3_MMDC1_Watt_t, 1},
	{"IEDMODEL_DER3_MMDC1_Vol_mag", IEDMODEL_DER3_MMDC1_Vol_mag_i, IEDMODEL_DER3_MMDC1_Vol_mag_i, IEDMODEL_DER3_MMDC1_Vol_t, 1},
	{"IEDMODEL_DER3_MMDC1_Amp_mag", IEDMODEL_DER3_MMDC1_Amp_mag_i, IEDMODEL_DER3_MMDC1_Amp_mag_i, IEDMODEL_DER3_MMDC1_Amp_t, 1},



	{"IEDMODEL_DER3_CSWI1_Pos_stVal", IEDMODEL_DER3_CSWI1_Pos_stVal, IEDMODEL_DER3_CSWI1_Pos_stVal, IEDMODEL_DER3_CSWI1_Pos_t, 1},
	{"IEDMODEL_DER3_CSWI1_PosA_stVal", IEDMODEL_DER3_CSWI1_PosA_stVal, IEDMODEL_DER3_CSWI1_PosA_stVal, IEDMODEL_DER3_CSWI1_PosA_t, 1},
	{"IEDMODEL_DER3_CSWI1_PosB_stVal", IEDMODEL_DER3_CSWI1_PosB_stVal, IEDMODEL_DER3_CSWI1_PosB_stVal, IEDMODEL_DER3_CSWI1_PosB_t, 1},
	{"IEDMODEL_DER3_CSWI1_PosC_stVal", IEDMODEL_DER3_CSWI1_PosC_stVal, IEDMODEL_DER3_CSWI1_PosC_stVal, IEDMODEL_DER3_CSWI1_PosC_t, 1},
	{"IEDMODEL_DER3_CSWI1_OpCntRs_stVal", IEDMODEL_DER3_CSWI1_OpCntRs_stVal, IEDMODEL_DER3_CSWI1_OpCntRs_stVal, IEDMODEL_DER3_CSWI1_OpCntRs_t, 1},	
	{"IEDMODEL_DER3_XSWI1_Pos_stVal", IEDMODEL_DER3_XSWI1_Pos_stVal, IEDMODEL_DER3_XSWI1_Pos_stVal, IEDMODEL_DER3_XSWI1_Pos_t, 1},
	{"IEDMODEL_DER3_XSWI1_BlkOpn_stVal", IEDMODEL_DER3_XSWI1_BlkOpn_stVal, IEDMODEL_DER3_XSWI1_BlkOpn_stVal, IEDMODEL_DER3_XSWI1_BlkOpn_t, 1},
	{"IEDMODEL_DER3_XSWI1_BlkCls_stVal", IEDMODEL_DER3_XSWI1_BlkCls_stVal, IEDMODEL_DER3_XSWI1_BlkCls_stVal, IEDMODEL_DER3_XSWI1_BlkCls_t, 1},
	{"IEDMODEL_DER3_XSWI1_Loc_stVal", IEDMODEL_DER3_XSWI1_Loc_stVal, IEDMODEL_DER3_XSWI1_Loc_stVal, IEDMODEL_DER3_XSWI1_Loc_t, 1},
	{"IEDMODEL_DER3_XSWI1_OpCnt_stVal", IEDMODEL_DER3_XSWI1_OpCnt_stVal, IEDMODEL_DER3_XSWI1_OpCnt_stVal, IEDMODEL_DER3_XSWI1_OpCnt_t, 1},
	{"IEDMODEL_DER3_XSWI1_ChaMotEna_stVal", IEDMODEL_DER3_XSWI1_ChaMotEna_stVal, IEDMODEL_DER3_XSWI1_ChaMotEna_stVal, IEDMODEL_DER3_XSWI1_ChaMotEna_t, 1},
	{"IEDMODEL_DER3_XSWI1_LocSta_stVal", IEDMODEL_DER3_XSWI1_LocSta_stVal, IEDMODEL_DER3_XSWI1_LocSta_stVal, IEDMODEL_DER3_XSWI1_LocSta_t, 1},
	{"IEDMODEL_DER3_XSWI1_Dsc_stVal", IEDMODEL_DER3_XSWI1_Dsc_stVal, IEDMODEL_DER3_XSWI1_Dsc_stVal, IEDMODEL_DER3_XSWI1_Dsc_t, 1},
	{"IEDMODEL_DER3_XCBR1_Pos_stVal", IEDMODEL_DER3_XCBR1_Pos_stVal, IEDMODEL_DER3_XCBR1_Pos_stVal, IEDMODEL_DER3_XCBR1_Pos_t, 1},
	{"IEDMODEL_DER3_XCBR1_BlkCls_stVal", IEDMODEL_DER3_XCBR1_BlkCls_stVal, IEDMODEL_DER3_XCBR1_BlkCls_stVal, IEDMODEL_DER3_XCBR1_BlkCls_t, 1},
	{"IEDMODEL_DER3_XCBR1_BlkOpn_stVal", IEDMODEL_DER3_XCBR1_BlkOpn_stVal, IEDMODEL_DER3_XCBR1_BlkOpn_stVal, IEDMODEL_DER3_XCBR1_BlkOpn_t, 1},
	{"IEDMODEL_DER3_XCBR1_Loc_stVal", IEDMODEL_DER3_XCBR1_Loc_stVal, IEDMODEL_DER3_XCBR1_Loc_stVal, IEDMODEL_DER3_XCBR1_Loc_t, 1},
	{"IEDMODEL_DER3_XCBR1_OpCnt_stVal", IEDMODEL_DER3_XCBR1_OpCnt_stVal, IEDMODEL_DER3_XCBR1_OpCnt_stVal, IEDMODEL_DER3_XCBR1_OpCnt_t, 1},
	{"IEDMODEL_DER3_XCBR1_MaxOpCap_stVal", IEDMODEL_DER3_XCBR1_MaxOpCap_stVal, IEDMODEL_DER3_XCBR1_MaxOpCap_stVal, IEDMODEL_DER3_XCBR1_MaxOpCap_t, 1},
	{"IEDMODEL_DER3_XCBR1_ChaMotEna_stVal", IEDMODEL_DER3_XCBR1_ChaMotEna_stVal, IEDMODEL_DER3_XCBR1_ChaMotEna_stVal, IEDMODEL_DER3_XCBR1_ChaMotEna_t, 1},
	{"IEDMODEL_DER3_XCBR1_LocSta_stVal", IEDMODEL_DER3_XCBR1_LocSta_stVal, IEDMODEL_DER3_XCBR1_LocSta_stVal, IEDMODEL_DER3_XCBR1_LocSta_t, 1},
	
	{"IEDMODEL_DER3_ZBAT1_Vol_mag", IEDMODEL_DER3_ZBAT1_Vol_mag_i, IEDMODEL_DER3_ZBAT1_Vol_mag_i, IEDMODEL_DER3_ZBAT1_Vol_t, 1},
	{"IEDMODEL_DER3_ZBAT1_Amp_mag", IEDMODEL_DER3_ZBAT1_Amp_mag_i, IEDMODEL_DER3_ZBAT1_Amp_mag_i, IEDMODEL_DER3_ZBAT1_Amp_t, 1},
	{"IEDMODEL_DER3_ZBAT1_BatTest_stVal", IEDMODEL_DER3_ZBAT1_BatTest_stVal, IEDMODEL_DER3_ZBAT1_BatTest_stVal, IEDMODEL_DER3_ZBAT1_BatTest_t, 1},
	{"IEDMODEL_DER3_ZBAT1_VolChgRte_mag", IEDMODEL_DER3_ZBAT1_VolChgRte_mag_i, IEDMODEL_DER3_ZBAT1_VolChgRte_mag_i, IEDMODEL_DER3_ZBAT1_VolChgRte_t, 1},
	{"IEDMODEL_DER3_ZBAT1_BatHi_stVal", IEDMODEL_DER3_ZBAT1_BatHi_stVal, IEDMODEL_DER3_ZBAT1_BatHi_stVal, IEDMODEL_DER3_ZBAT1_BatHi_t, 1},
	{"IEDMODEL_DER3_ZBAT1_BatLo_stVal", IEDMODEL_DER3_ZBAT1_BatLo_stVal, IEDMODEL_DER3_ZBAT1_BatLo_stVal, IEDMODEL_DER3_ZBAT1_BatLo_t, 1},
	
	
	{"IEDMODEL_DER3_XCBR1_LocSta_stVal", IEDMODEL_DER3_XCBR1_LocSta_stVal, IEDMODEL_DER3_XCBR1_LocSta_stVal, IEDMODEL_DER3_XCBR1_LocSta_t, 1},
	{"IEDMODEL_DER3_XCBR1_LocSta_stVal", IEDMODEL_DER3_XCBR1_LocSta_stVal, IEDMODEL_DER3_XCBR1_LocSta_stVal, IEDMODEL_DER3_XCBR1_LocSta_t, 1},
	{"IEDMODEL_DER3_XCBR1_LocSta_stVal", IEDMODEL_DER3_XCBR1_LocSta_stVal, IEDMODEL_DER3_XCBR1_LocSta_stVal, IEDMODEL_DER3_XCBR1_LocSta_t, 1},
	{"IEDMODEL_DER3_XCBR1_LocSta_stVal", IEDMODEL_DER3_XCBR1_LocSta_stVal, IEDMODEL_DER3_XCBR1_LocSta_stVal, IEDMODEL_DER3_XCBR1_LocSta_t, 1},
	{"IEDMODEL_DER3_XCBR1_LocSta_stVal", IEDMODEL_DER3_XCBR1_LocSta_stVal, IEDMODEL_DER3_XCBR1_LocSta_stVal, IEDMODEL_DER3_XCBR1_LocSta_t, 1},
	{"IEDMODEL_DER3_XCBR1_LocSta_stVal", IEDMODEL_DER3_XCBR1_LocSta_stVal, IEDMODEL_DER3_XCBR1_LocSta_stVal, IEDMODEL_DER3_XCBR1_LocSta_t, 1},
	{"IEDMODEL_DER3_XCBR1_LocSta_stVal", IEDMODEL_DER3_XCBR1_LocSta_stVal, IEDMODEL_DER3_XCBR1_LocSta_stVal, IEDMODEL_DER3_XCBR1_LocSta_t, 1},
	
	{"IEDMODEL_DER3_PTOV1_Str_general", IEDMODEL_DER3_PTOV1_Str_general, IEDMODEL_DER3_PTOV1_Str_general, IEDMODEL_DER3_PTOV1_Str_t, 1},
	{"IEDMODEL_DER3_PTOV1_Op_general", IEDMODEL_DER3_PTOV1_Op_general, IEDMODEL_DER3_PTOV1_Op_general, IEDMODEL_DER3_PTOV1_Op_t, 1},
	
	{"IEDMODEL_DER3_PTOC1_Str_general", IEDMODEL_DER3_PTOC1_Str_general, IEDMODEL_DER3_PTOC1_Str_general, IEDMODEL_DER3_PTOC1_Str_t, 1},
	{"IEDMODEL_DER3_PTOC1_Op_general", IEDMODEL_DER3_PTOC1_Op_general, IEDMODEL_DER3_PTOC1_Op_general, IEDMODEL_DER3_PTOC1_Op_t, 1},
	
	{"IEDMODEL_DER3_DVER1_Mir_stVal", IEDMODEL_DER3_DVER1_Mir_stVal, IEDMODEL_DER3_DVER1_Mir_stVal, IEDMODEL_DER3_DVER1_Mir_t, 1},
	{"IEDMODEL_DER3_DVER1_ClcStr_stVal", IEDMODEL_DER3_DVER1_ClcStr_stVal, IEDMODEL_DER3_DVER1_ClcStr_stVal, IEDMODEL_DER3_DVER1_ClcStr_t, 1},
	{"IEDMODEL_DER3_DVER1_Beh_stVal", IEDMODEL_DER3_DVER1_Beh_stVal, IEDMODEL_DER3_DVER1_Beh_stVal, IEDMODEL_DER3_DVER1_Beh_t, 1},
	{"IEDMODEL_DER3_DVER1_ClcMth_stVal", IEDMODEL_DER3_DVER1_ClcMth_setVal, IEDMODEL_DER3_DVER1_ClcMth_setVal, IEDMODEL_DER3_DVER1_Beh_t, 0},
	
	{"IEDMODEL_DER3_DPCC1_Mir_stVal", IEDMODEL_DER3_DPCC1_Mir_stVal, IEDMODEL_DER3_DPCC1_Mir_stVal, IEDMODEL_DER3_DPCC1_Mir_t, 1},
	{"IEDMODEL_DER3_DPCC1_ClcStr_stVal", IEDMODEL_DER3_DPCC1_ClcStr_stVal, IEDMODEL_DER3_DPCC1_ClcStr_stVal, IEDMODEL_DER3_DPCC1_ClcStr_t, 1},
	{"IEDMODEL_DER3_DPCC1_Beh_stVal", IEDMODEL_DER3_DPCC1_Beh_stVal, IEDMODEL_DER3_DPCC1_Beh_stVal, IEDMODEL_DER3_DPCC1_Beh_t, 1},
	{"IEDMODEL_DER3_DPCC1_AreaEpsWMax_setMag", IEDMODEL_DER3_DPCC1_AreaEpsWMax_setMag_i, IEDMODEL_DER3_DPCC1_AreaEpsWMax_setMag_i, IEDMODEL_DER3_DPCC1_Beh_t, 0},
	{"IEDMODEL_DER3_DPCC1_VRef_setMag", IEDMODEL_DER3_DPCC1_VRef_setMag_i, IEDMODEL_DER3_DPCC1_VRef_setMag_i, IEDMODEL_DER3_DPCC1_Beh_t, 0},
	{"IEDMODEL_DER3_DPCC1_RefFrm_setVal", IEDMODEL_DER3_DPCC1_RefFrm_setVal, IEDMODEL_DER3_DPCC1_RefFrm_setVal, IEDMODEL_DER3_DPCC1_Beh_t, 0},
	{"IEDMODEL_DER3_DPCC1_ClcMth_setVal", IEDMODEL_DER3_DPCC1_ClcMth_setVal, IEDMODEL_DER3_DPCC1_ClcMth_setVal, IEDMODEL_DER3_DPCC1_Beh_t, 0},

	{"IEDMODEL_DER3_DECP1_Mir_stVal", IEDMODEL_DER3_DECP1_Mir_stVal, IEDMODEL_DER3_DECP1_Mir_stVal, IEDMODEL_DER3_DECP1_Mir_t, 1},
	{"IEDMODEL_DER3_DECP1_ClcStr_stVal", IEDMODEL_DER3_DPCC1_ClcStr_stVal, IEDMODEL_DER3_DECP1_ClcStr_stVal, IEDMODEL_DER3_DECP1_ClcStr_t, 1},
	{"IEDMODEL_DER3_DECP1_Beh_stVal", IEDMODEL_DER3_DECP1_Beh_stVal, IEDMODEL_DER3_DECP1_Beh_stVal, IEDMODEL_DER3_DECP1_Beh_t, 1},
	{"IEDMODEL_DER3_DECP1_VRef_setMag", IEDMODEL_DER3_DECP1_VRef_setMag_i, IEDMODEL_DER3_DECP1_VRef_setMag_i, IEDMODEL_DER3_DECP1_Beh_t, 0},
	{"IEDMODEL_DER3_DECP1_RefFrm_setVal", IEDMODEL_DER3_DECP1_RefFrm_setVal, IEDMODEL_DER3_DECP1_RefFrm_setVal, IEDMODEL_DER3_DECP1_Beh_t, 0},
	{"IEDMODEL_DER3_DECP1_ClcMth_setVal", IEDMODEL_DER3_DECP1_ClcMth_setVal, IEDMODEL_DER3_DECP1_ClcMth_setVal, IEDMODEL_DER3_DECP1_Beh_t, 0},
	
	{"IEDMODEL_DER3_DSTO1_Mir_stVal", IEDMODEL_DER3_DSTO1_Mir_stVal, IEDMODEL_DER3_DSTO1_Mir_stVal, IEDMODEL_DER3_DSTO1_Mir_t, 1},
	{"IEDMODEL_DER3_DSTO1_ClcStr_stVal", IEDMODEL_DER3_DSTO1_ClcStr_stVal, IEDMODEL_DER3_DSTO1_ClcStr_stVal, IEDMODEL_DER3_DSTO1_ClcStr_t, 1},
	{"IEDMODEL_DER3_DSTO1_DEROpSt_stVal", IEDMODEL_DER3_DSTO1_DEROpSt_stVal, IEDMODEL_DER3_DSTO1_DEROpSt_stVal, IEDMODEL_DER3_DSTO1_DEROpSt_t, 1},
	{"IEDMODEL_DER3_DSTO1_Beh_stVal", IEDMODEL_DER3_DSTO1_Beh_stVal, IEDMODEL_DER3_DSTO1_Beh_stVal, IEDMODEL_DER3_DSTO1_Beh_t, 1},
	{"IEDMODEL_DER3_DSTO1_PhsConnTyp_setVal", IEDMODEL_DER3_DSTO1_PhsConnTyp_setVal, IEDMODEL_DER3_DSTO1_PhsConnTyp_setVal, IEDMODEL_DER3_DSTO1_Beh_t, 0},
	{"IEDMODEL_DER3_DSTO1_DERTyp_setVal", IEDMODEL_DER3_DSTO1_DERTyp_setVal, IEDMODEL_DER3_DSTO1_DERTyp_setVal, IEDMODEL_DER3_DSTO1_Beh_t, 0},
	{"IEDMODEL_DER3_DSTO1_ClcMth_setVal", IEDMODEL_DER3_DSTO1_ClcMth_setVal, IEDMODEL_DER3_DSTO1_ClcMth_setVal, IEDMODEL_DER3_DSTO1_Beh_t, 0},
	
	{"IEDMODEL_DER3_DBAT1_Mir_stVal", IEDMODEL_DER3_DBAT1_Mir_stVal, IEDMODEL_DER3_DBAT1_Mir_stVal, IEDMODEL_DER3_DBAT1_Mir_t, 1},
	{"IEDMODEL_DER3_DBAT1_ClcStr_stVal", IEDMODEL_DER3_DBAT1_ClcStr_stVal, IEDMODEL_DER3_DBAT1_ClcStr_stVal, IEDMODEL_DER3_DBAT1_ClcStr_t, 1},
	{"IEDMODEL_DER3_DBAT1_Beh_stVal", IEDMODEL_DER3_DBAT1_Beh_stVal, IEDMODEL_DER3_DBAT1_Beh_stVal, IEDMODEL_DER3_DBAT1_Beh_t, 1},
	{"IEDMODEL_DER3_DBAT1_ClcMth_setVal", IEDMODEL_DER3_DBAT1_ClcMth_setVal, IEDMODEL_DER3_DBAT1_ClcMth_setVal, IEDMODEL_DER3_DBAT1_Beh_t, 0},
	{"IEDMODEL_DER3_DBAT1_BatTyp_setVal", IEDMODEL_DER3_DBAT1_BatTyp_setVal, IEDMODEL_DER3_DBAT1_BatTyp_setVal, IEDMODEL_DER3_DBAT1_Beh_t, 0},	
	
	{"IEDMODEL_DER3_SBAT1_Mir_stVal", IEDMODEL_DER3_SBAT1_Mir_stVal, IEDMODEL_DER3_SBAT1_Mir_stVal, IEDMODEL_DER3_SBAT1_Mir_t, 1},
	{"IEDMODEL_DER3_SBAT1_ClcStr_stVal", IEDMODEL_DER3_SBAT1_ClcStr_stVal, IEDMODEL_DER3_SBAT1_ClcStr_stVal, IEDMODEL_DER3_SBAT1_ClcStr_t, 1},
	{"IEDMODEL_DER3_SBAT1_Beh_stVal", IEDMODEL_DER3_SBAT1_Beh_stVal, IEDMODEL_DER3_SBAT1_Beh_stVal, IEDMODEL_DER3_SBAT1_Beh_t, 1},
	{"IEDMODEL_DER3_SBAT1_ClcMth_setVal", IEDMODEL_DER3_SBAT1_ClcMth_setVal, IEDMODEL_DER3_SBAT1_ClcMth_setVal, IEDMODEL_DER3_SBAT1_Beh_t, 0},
		
};

/*type 0 bool
type 1 timestamp*/


struct get_api ABC[500] = {
    {"IEDMODEL_DER3_GGIO1_SPCSO1_stVal", IEDMODEL_DER3_GGIO1_SPCSO1_stVal, boolen_value},
    {"IEDMODEL_DER3_GGIO1_DPCSO1_stVal", IEDMODEL_DER3_GGIO1_DPCSO1_stVal, boolen_value},
    {"IEDMODEL_DER3_GGIO1_ISCSO1_stVal", IEDMODEL_DER3_GGIO1_ISCSO1_stVal, int_value},
    {"IEDMODEL_DER3_GGIO1_SPCSO1_t", IEDMODEL_DER3_GGIO1_SPCSO1_t, timestamp_value},
    {"IEDMODEL_DER3_GGIO1_OpCntRs_stVal", IEDMODEL_DER3_GGIO1_OpCntRs_stVal, int_value},
    {"IEDMODEL_DER3_MMXU1_TotW_mag", IEDMODEL_DER3_MMXU1_TotW_mag_i, int_value},
    {"IEDMODEL_DER3_MMXU1_TotVAr_mag", IEDMODEL_DER3_MMXU1_TotVAr_mag_i, int_value},
    {"IEDMODEL_DER3_MMXU1_TotVA_mag", IEDMODEL_DER3_MMXU1_TotVA_mag_i, int_value},
    {"IEDMODEL_DER3_MMXU1_TotPF_mag", IEDMODEL_DER3_MMXU1_TotPF_mag_i, int_value},
    {"IEDMODEL_DER3_MMXU1_Hz_mag", IEDMODEL_DER3_MMXU1_Hz_mag_i, int_value},
    {"IEDMODEL_DER3_MMXU1_PPV_phsAB", IEDMODEL_DER3_MMXU1_PPV_phsAB_cVal_mag_i, int_value},
    {"IEDMODEL_DER3_MMXU1_PPV_phsBC", IEDMODEL_DER3_MMXU1_PPV_phsBC_cVal_mag_i, int_value},
    {"IEDMODEL_DER3_MMXU1_PPV_phsCA", IEDMODEL_DER3_MMXU1_PPV_phsCA_cVal_mag_i, int_value},
    {"IEDMODEL_DER3_MMXU1_PNV_phsA", IEDMODEL_DER3_MMXU1_PNV_phsA_cVal_mag_i, int_value},
    {"IEDMODEL_DER3_MMXU1_PNV_phsB", IEDMODEL_DER3_MMXU1_PNV_phsB_cVal_mag_i, int_value},
    {"IEDMODEL_DER3_MMXU1_PNV_phsC", IEDMODEL_DER3_MMXU1_PNV_phsC_cVal_mag_i, int_value},
    {"IEDMODEL_DER3_MMXU1_A_phsA", IEDMODEL_DER3_MMXU1_A_phsA_cVal_mag_i, int_value},
    {"IEDMODEL_DER3_MMXU1_A_phsB", IEDMODEL_DER3_MMXU1_A_phsB_cVal_mag_i, int_value},
    {"IEDMODEL_DER3_MMXU1_A_phsC", IEDMODEL_DER3_MMXU1_A_phsC_cVal_mag_i, int_value},
    {"IEDMODEL_DER3_MMXU1_PNV_phsA", IEDMODEL_DER3_MMXU1_PNV_phsA_cVal_mag_f, float_value},

    {"IEDMODEL_DER3_MMDC1_Amp_mag", IEDMODEL_DER3_MMDC1_Amp_mag_i, int_value},
    {"IEDMODEL_DER3_MMDC1_Vol_mag", IEDMODEL_DER3_MMDC1_Vol_mag_i, int_value},
    {"IEDMODEL_DER3_MMDC1_Watt_mag", IEDMODEL_DER3_MMDC1_Watt_mag_i, int_value},
   
    {"IEDMODEL_DER3_CSWI1_Pos_stVal", IEDMODEL_DER3_CSWI1_Pos_stVal, Dbpos_type_value},
    {"IEDMODEL_DER3_CSWI1_PosA_stVal", IEDMODEL_DER3_CSWI1_PosA_stVal, Dbpos_type_value},
    {"IEDMODEL_DER3_CSWI1_PosB_stVal", IEDMODEL_DER3_CSWI1_PosB_stVal, Dbpos_type_value},
    {"IEDMODEL_DER3_CSWI1_PosC_stVal", IEDMODEL_DER3_CSWI1_PosC_stVal, Dbpos_type_value},
    {"IEDMODEL_DER3_CSWI1_OpCntRs_stVal", IEDMODEL_DER3_CSWI1_OpCntRs_stVal, int_value},
    {"IEDMODEL_DER3_XSWI1_Pos_stVal", IEDMODEL_DER3_XSWI1_Pos_stVal, Dbpos_type_value},
    {"IEDMODEL_DER3_XSWI1_BlkOpn_stVal", IEDMODEL_DER3_XSWI1_BlkOpn_stVal, boolen_value},
    {"IEDMODEL_DER3_XSWI1_BlkCls_stVal", IEDMODEL_DER3_XSWI1_BlkCls_stVal, boolen_value},
    {"IEDMODEL_DER3_XSWI1_Loc_stVal", IEDMODEL_DER3_XSWI1_Loc_stVal, boolen_value},
    {"IEDMODEL_DER3_XSWI1_OpCnt_stVal", IEDMODEL_DER3_XSWI1_OpCnt_stVal, int_value},
    {"IEDMODEL_DER3_XSWI1_ChaMotEna_stVal", IEDMODEL_DER3_XSWI1_ChaMotEna_stVal, boolen_value},
    {"IEDMODEL_DER3_XSWI1_LocSta_stVal", IEDMODEL_DER3_XSWI1_LocSta_stVal, boolen_value},
    {"IEDMODEL_DER3_XSWI1_Dsc_stVal", IEDMODEL_DER3_XSWI1_Dsc_stVal, boolen_value},
    {"IEDMODEL_DER3_XCBR1_Pos_stVal", IEDMODEL_DER3_XCBR1_Pos_stVal, Dbpos_type_value},
    {"IEDMODEL_DER3_XCBR1_BlkCls_stVal", IEDMODEL_DER3_XCBR1_BlkCls_stVal, boolen_value},
    {"IEDMODEL_DER3_XCBR1_BlkOpn_stVal", IEDMODEL_DER3_XCBR1_BlkOpn_stVal, boolen_value},
    
    {"IEDMODEL_DER3_XCBR1_Loc_stVal", IEDMODEL_DER3_XCBR1_Loc_stVal, boolen_value},
    {"IEDMODEL_DER3_XCBR1_OpCnt_stVal", IEDMODEL_DER3_XCBR1_OpCnt_stVal, int_value},
    {"IEDMODEL_DER3_XCBR1_MaxOpCap_stVal", IEDMODEL_DER3_XCBR1_MaxOpCap_stVal, int_value},
    {"IEDMODEL_DER3_XCBR1_ChaMotEna_stVal", IEDMODEL_DER3_XCBR1_ChaMotEna_stVal, boolen_value},
    {"IEDMODEL_DER3_XCBR1_LocSta_stVal", IEDMODEL_DER3_XCBR1_LocSta_stVal, boolen_value},
    
    {"IEDMODEL_DER3_ZBAT1_Vol_mag", IEDMODEL_DER3_ZBAT1_Vol_mag_i, int_value},
    {"IEDMODEL_DER3_ZBAT1_Amp_mag", IEDMODEL_DER3_ZBAT1_Amp_mag_i, int_value},
    {"IEDMODEL_DER3_ZBAT1_BatTest_stVal", IEDMODEL_DER3_ZBAT1_BatTest_stVal, boolen_value},
    {"IEDMODEL_DER3_ZBAT1_VolChgRte_mag", IEDMODEL_DER3_ZBAT1_VolChgRte_mag_i, int_value},
    {"IEDMODEL_DER3_ZBAT1_BatHi_stVal", IEDMODEL_DER3_ZBAT1_BatHi_stVal, boolen_value},
    {"IEDMODEL_DER3_ZBAT1_BatLo_stVal", IEDMODEL_DER3_ZBAT1_BatLo_stVal, boolen_value},
    {"IEDMODEL_DER3_PTOV1_Str_general", IEDMODEL_DER3_PTOV1_Str_general, boolen_value},
    {"IEDMODEL_DER3_PTOV1_Op_general", IEDMODEL_DER3_PTOV1_Op_general, boolen_value},
    
    {"IEDMODEL_DER3_PTOC1_Str_general", IEDMODEL_DER3_PTOC1_Str_general, boolen_value},
    {"IEDMODEL_DER3_PTOC1_Op_general", IEDMODEL_DER3_PTOC1_Op_general, boolen_value},
    
    {"IEDMODEL_DER3_PTOV1_Str_general", IEDMODEL_DER3_PTOV1_Str_general, boolen_value},
    {"IEDMODEL_DER3_PTOV1_Op_general", IEDMODEL_DER3_PTOV1_Op_general, boolen_value},
    
    {"IEDMODEL_DER3_DVER1_Mir_stVal", IEDMODEL_DER3_DVER1_Mir_stVal, boolen_value},
    {"IEDMODEL_DER3_DVER1_ClcStr_stVal", IEDMODEL_DER3_DVER1_ClcStr_stVal, boolen_value},
    {"IEDMODEL_DER3_DVER1_ClcMth_setVal", IEDMODEL_DER3_DVER1_ClcMth_setVal, int_value},
    {"IEDMODEL_DER3_DVER1_Beh_stVal", IEDMODEL_DER3_DVER1_Beh_stVal, int_value},
	
    {"IEDMODEL_DER3_DPCC1_Mir_stVal", IEDMODEL_DER3_DPCC1_Mir_stVal, boolen_value},
    {"IEDMODEL_DER3_DPCC1_ClcStr_stVal", IEDMODEL_DER3_DPCC1_ClcStr_stVal, boolen_value},
    {"IEDMODEL_DER3_DPCC1_Beh_stVal", IEDMODEL_DER3_DPCC1_Beh_stVal, int_value},
    {"IEDMODEL_DER3_DPCC1_AreaEpsWMax_setMag", IEDMODEL_DER3_DPCC1_AreaEpsWMax_setMag_i, int_value},
    {"IEDMODEL_DER3_DPCC1_VRef_setMag", IEDMODEL_DER3_DPCC1_VRef_setMag_i, int_value},
    {"IEDMODEL_DER3_DPCC1_RefFrm_setVal", IEDMODEL_DER3_DPCC1_RefFrm_setVal, boolen_value},
    {"IEDMODEL_DER3_DPCC1_ClcMth_setVal", IEDMODEL_DER3_DPCC1_ClcMth_setVal, int_value},

    {"IEDMODEL_DER3_DECP1_Mir_stVal", IEDMODEL_DER3_DECP1_Mir_stVal, boolen_value},
    {"IEDMODEL_DER3_DECP1_ClcStr_stVal", IEDMODEL_DER3_DPCC1_ClcStr_stVal, boolen_value},
    {"IEDMODEL_DER3_DECP1_Beh_stVal", IEDMODEL_DER3_DECP1_Beh_stVal, int_value},
    {"IEDMODEL_DER3_DECP1_VRef_setMag", IEDMODEL_DER3_DECP1_VRef_setMag_i, int_value},
    {"IEDMODEL_DER3_DECP1_RefFrm_setVal", IEDMODEL_DER3_DECP1_RefFrm_setVal, boolen_value},
    {"IEDMODEL_DER3_DECP1_ClcMth_setVal", IEDMODEL_DER3_DECP1_ClcMth_setVal, int_value},
	
    {"IEDMODEL_DER3_DSTO1_Mir_stVal", IEDMODEL_DER3_DSTO1_Mir_stVal, boolen_value},
    {"IEDMODEL_DER3_DSTO1_ClcStr_stVal", IEDMODEL_DER3_DSTO1_ClcStr_stVal, boolen_value},
    {"IEDMODEL_DER3_DSTO1_DEROpSt_stVal", IEDMODEL_DER3_DSTO1_DEROpSt_stVal, int_value},
    {"IEDMODEL_DER3_DSTO1_Beh_stVal", IEDMODEL_DER3_DSTO1_Beh_stVal, int_value},
    {"IEDMODEL_DER3_DSTO1_PhsConnTyp_setVal", IEDMODEL_DER3_DSTO1_PhsConnTyp_setVal, int_value},
    {"IEDMODEL_DER3_DSTO1_DERTyp_setVal", IEDMODEL_DER3_DSTO1_DERTyp_setVal, int_value},
    {"IEDMODEL_DER3_DSTO1_ClcMth_setVal", IEDMODEL_DER3_DSTO1_ClcMth_setVal, int_value}, 
	
    {"IEDMODEL_DER3_DBAT1_Mir_stVal", IEDMODEL_DER3_DBAT1_Mir_stVal, boolen_value},
    {"IEDMODEL_DER3_DBAT1_ClcStr_stVal", IEDMODEL_DER3_DBAT1_ClcStr_stVal, boolen_value},
    {"IEDMODEL_DER3_DBAT1_Beh_stVal", IEDMODEL_DER3_DBAT1_Beh_stVal, int_value},
    {"IEDMODEL_DER3_DBAT1_ClcMth_setVal", IEDMODEL_DER3_DBAT1_ClcMth_setVal, int_value},
    {"IEDMODEL_DER3_DBAT1_BatTyp_setVal", IEDMODEL_DER3_DBAT1_BatTyp_setVal, int_value},
	
    {"IEDMODEL_DER3_SBAT1_Mir_stVal", IEDMODEL_DER3_SBAT1_Mir_stVal, boolen_value},
    {"IEDMODEL_DER3_SBAT1_ClcStr_stVal", IEDMODEL_DER3_SBAT1_ClcStr_stVal, boolen_value},
    {"IEDMODEL_DER3_SBAT1_Beh_stVal", IEDMODEL_DER3_SBAT1_Beh_stVal, int_value},
    {"IEDMODEL_DER3_SBAT1_ClcMth_setVal", IEDMODEL_DER3_SBAT1_ClcMth_setVal, int_value},
    
};



#endif
